DROP TABLE PERSON;

CREATE TABLE IF NOT EXISTS PERSON(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    SURNAME VARCHAR(255)
);

INSERT INTO PERSON(NAME, SURNAME) VALUES('Sergey', 'Esenin');
INSERT INTO PERSON(NAME, SURNAME) VALUES('Alexander', 'Poushkine');
INSERT INTO PERSON(NAME, SURNAME) VALUES('Michail', 'Lermontov');
INSERT INTO PERSON(NAME, SURNAME) VALUES('Joseph', 'Brodsky');
